canonical/charm-relation-interfaces

- interfaces/kafka_client/v0/README.md
- interfaces/kafka_client/v0/schemas/provider.json
For Kafka, `endpoints` and `uri` are somewhat redundant. In Kafka there is the notion of `bootstrap_servers` that seems to overlap with either one of the two. 
After talking to @delgod, @marcoppenheimer and @welpaolo , it seemed reasonable to us to keep `endpoints` only, that is the more general parameter between the two.
> [KAFKA] Remove URI parameter from the interface

- README.md
- interfaces/__template__/v0/README.md
- interfaces/__template__/v0/charms.yaml
- interfaces/__template__/v0/schemas/provider.json
- interfaces/__template__/v0/schemas/requirer.json
added a `interfaces.__template__` folder:
```
./interfaces/__template__
└── v0
├── charms.yaml
├── README.md
└── schemas
├── provider.json
└── requirer.json
```
That should help users quickly get started contributing their interface.
Also, when we add the interface testers, we are going to add `interfaces/__template__/v0/interface_tests/interface_tests.py` to the template, which is going to be very useful to get people used to the testing framework.
> added interface directory template

- README.md
- interfaces/opensearch_client/v0/README.md
- interfaces/opensearch_client/v0/charms.yaml
- interfaces/opensearch_client/v0/schemas/provider.json
- interfaces/opensearch_client/v0/schemas/requirer.json
This is a first draft spec for the opensearch interface 
- `database` field has been replaced with `index`
- `read_only_endpoints` aren't in this relation, since they're not really relevant to opensearch. 
I'm still fixing up the tests, but you can see the interface in action [here](https://github.com/canonical/opensearch-operator/pull/30/). 
The spec is detailed below: 
---
This relation interface describes the expected behaviour of any charm interfacing with OpenSearch or ElasticSearch charms, such as the [Charmed OpenSearch Operator](https://github.com/canonical/opensearch-operator) using the `opensearch-client` relation.
In most cases, this will be accomplished using the [data_interfaces library](https://github.com/canonical/data-platform-libs/blob/main/lib/charms/data_platform_libs/v0 …
> Add draft opensearch interface 

- README.md
As the interface spec library continues to grow, the readme will soon become quite unwieldy to parse and navigate. As suggested by @massigori in a verbal conversation, we suggest to break it into internal and public interfaces. I took the liberty to break the internal interface list up on a per project basis.
- @massigori: Should `hydra_endpoints` move into internal?
- @delgod: Should `database_backup` move into internal?
- @Lukewh: when this merges, some adjustments **might** be required in the charmhub interfaces page, depending on how the scraping is implemented.
> docs: split list into project-internal and public interfaces

- README.md
- interfaces/kratos_endpoints/v0/README.md
- interfaces/kratos_endpoints/v0/charms.yaml
- interfaces/kratos_endpoints/v0/schemas/provider.json
`identity-platform-login-ui-operator` requires Kratos' public API endpoint, which will usually be exposed through Ingress using `traefik-k8s` charm. This interface is similar to [hydra-endpoints](https://github.com/canonical/charm-relation-interfaces/pull/45).
To summarize this relation, Kratos needs to provide its endpoints to Login UI charm.
In future we plan to create an Admin UI charm which will need Kratos' admin endpoint, thus this relation interface provides both admin and public endpoints - we'd like to keep it reusable across different charms in IAM stack.
> Add kratos_endpoints relation interface

- interfaces/mongodb_client/v0/README.md
- interfaces/mysql_client/v0/README.md
- interfaces/opensearch_client/v0/README.md
- interfaces/postgresql_client/v0/README.md
[data_interfaces](https://github.com/canonical/data-platform-libs/blob/main/lib/charms/data_platform_libs/v0/data_interfaces.py) currently sets requires data in the application databag, not the unit databag
> Update database requires to match data interfaces

- README.md
- docs/json_schemas/fiveg_nrf/v0/provider.json
- docs/json_schemas/fiveg_nrf/v0/requirer.json
- interfaces/fiveg_nrf/v0/README.md
- interfaces/fiveg_nrf/v0/charms.yaml
- interfaces/fiveg_nrf/v0/schema.py
Within 5G, the Network Repository Function (NRF) is responsible for providing information about discovered network function instances. This relation interface describes the expected behavior of any charm claiming to be able to provide or consume NRF information.
- https://www.iplook.com/products/5gc-nrf#:~:text=NRF%2C%20one%20of%20the%20network,discovered)%20to%20another%20NF%20instance.
- https://docs.google.com/document/d/1GDDrwXhICAK0ttBCMYlnZ6TEc2QSnxcR_jKMxMr59pE/edit
> Implementation of the 5G NRF interface

- .github/workflows/discover.yaml
This PR adds a 'discover' workflow action that allows us to run `interface_tester discover` on, for example, a PR branch.
The idea is that when reviewing e.g. #55 or #59 we can click on a 'Discover' button in the GH UI and see, for example:
```
Discovered:
login_ui_endpoints:
- v0:
- requirer:
- <no tests>
- schema NOT OK
- <no charms>
- provider:
- <no tests>
- schema OK
- charms:
- identity-platform-login-ui-operator (https://github.com/canonical/identity-platform-login-ui-operator) custom_test_setup=no
```
which tells us that the requirer schema is not correctly implemented and that no interface tests are present.
This makes reviewing PRs somewhat easier; otherwise it's harder to verify that tests being added or schemas being modified are correctly gathered by the same code that will …
> discover ci step

- README.md
- docs/json_schemas/ip_router/v0/provider.json
- docs/json_schemas/ip_router/v0/requirer.json
- interfaces/ip_router/v0/README.md
- interfaces/ip_router/v0/charms.yaml
- interfaces/ip_router/v0/schema.py
This PR includes the implementation of the IP router interface. This interface will be used by charms providing and requiring IP routing. The first use case is withing SD-Core where users will need to specify 3 different networks and have charms with multiple network interfaces on those networks (using Multus). For more information about this use case, you can read [this specification](https://docs.google.com/document/d/1nJBEfPw-k9YDWpqV-qrhZnfsJXyrnrjS-Q2SNnhdPrY/edit).
> Implementation of the `ip_router` interface

- interfaces/prometheus_scrape/v0/README.md
Update prometheus_scrape interface to reflect that the data is a string rather than a native JSON object.
> Express relation data for prometheus_scrape as string rather than native JSON object

- docs/json_schemas/tracing/v0/provider.json
- docs/json_schemas/tracing/v0/requirer.json
- interfaces/tracing/v0/README.md
- interfaces/tracing/v0/interface_tests/requirer_tests.py
- interfaces/tracing/v0/schema.py
requirer becomes provider and viceversa in the (still draft) `tracing` relation interface v0.
this change is required to address some CMR-related networking concerns, and it is somewhat more intuitive that tempo is seen as the provider of tracing (as a service) rather than the requirer of traces (as data).
> flip tracing relation directionality

- .github/workflows/discover.yaml
- docs/json_schemas/tracing/v0/provider.json
- interfaces/tracing/v0/interface_tests/provider_tests.py
- interfaces/tracing/v0/schema.py
- tox.ini
Currently, the tracing tests are outdated and error out with:
```
ERROR    interface_tester.interface_test:runner.py:55 Failed check 3: validating schema on scene output: 2 validation errors for ProviderSchema
app -> url
field required (type=value_error.missing)
app -> ingesters -> 0 -> protocol
field required (type=value_error.missing)
```
As well as:
```
File "/.../charm-relation-interfaces/.tox/build-json-schemas/lib/python3.10/site-packages/scenario/fs_mocks.py", line 7, in <module>
from ops.testing import _TestingFilesystem, _TestingStorageMount  # noqa
ImportError: cannot import name '_TestingFilesystem' from 'ops.testing' (/.../charm-relation-interfaces/.tox/build-json-schemas/lib/python3.10/site-packages/ops/testing.py)
```
This PR fixes those.
> Fix tracing test

- docs/json_schemas/ingress/v2/requirer.json
- interfaces/ingress/v2/README.md
- interfaces/ingress/v2/charms.yaml
- interfaces/ingress/v2/interface_tests/provider_tests.py
- interfaces/ingress/v2/schema.py
updated ingress v2 interface to reflect the fact that all fields are json-dumped yes, (even raw strings).
Checked against https://github.com/canonical/traefik-k8s-operator/actions/runs/5620534306/job/15229657054
> Ingress v2 json

- interfaces/ingress/v2/README.md
I find this statement strange as it means that the relation is not entirely defined here, and that depending on some implementation there could be extra fields which aren't validated, nor documented.
In my opinion this shouldn't be allowed, the relation should be clearly defined and any library, requirer, provider should strictly comply to that definition.
Any specific configuration should be managed in a `*-route` relation.
> Remove reference to additional config keys that may be supported

- README.md
- docs/json_schemas/fiveg_n4/v0/provider.json
- docs/json_schemas/fiveg_n4/v0/requirer.json
- interfaces/fiveg_n4/v0/README.md
- interfaces/fiveg_n4/v0/charms.yaml
- interfaces/fiveg_n4/v0/schema.py
**Overview:**
In 5G Core, the `N4` interface is used to establish a bridge between the User Plane and the Control Plane. 
A new charm relation interface facilitates connectivity over the N4 interface, between the interface provider and requirer.
**Reference:**
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g/edit
> Adding info about the fiveg_n4 interface

- interfaces/opensearch_client/v0/README.md
- interfaces/opensearch_client/v0/schemas/requirer.json
Introducing Juju Secerts in Charms Relations requires certain changes on data exchange between the Requirer and Provider charm involved.
This is our proposal for the new protocol, and changes on Relational Databag data fields, for Juju Secrets based information exchange.
> Juju Secrets to communicate sensitive information in Charm Relations (Opensearch)

- README.md
- docs/json_schemas/interfaces/sdcore_management/provider.json
- docs/json_schemas/interfaces/sdcore_management/requirer.json
- interfaces/sdcore_management/README.md
- interfaces/sdcore_management/charms.yaml
- interfaces/sdcore_management/schema.py
SD-Core Webui is used to configure SD-Core.
In Charmed-5G SD-Core NMS Operator provides a user interface that leverages SD-Core Webui Operator to configure the network based on user input.
This spec describes the relation interface that is needed that Webui to pass the needed url to the NMS.
> Creates sdcore management interface

- README.md
- docs/json_schemas/fiveg_gnb_identity/v0/provider.json
- docs/json_schemas/fiveg_gnb_identity/v0/requirer.json
- interfaces/fiveg_gnb_identity/v0/README.md
- interfaces/fiveg_gnb_identity/v0/charms.yaml
- interfaces/fiveg_gnb_identity/v0/schema.py
A charm relation interface for gNodeb’s to share their identity to charms that require those informations. 
Reference:
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g/edit
> Adding fiveg gnb identity relation interface

- docs/json_schemas/vault_kv/v0/requirer.json
- interfaces/vault_kv/v0/schema.py
For some items, no keywords was used to set the description, meaning the description was actually used as default value.
> Fix vault-kv schema description

- docs/json_schemas/fiveg_gnb_identity/v0/provider.json
- interfaces/fiveg_gnb_identity/v0/README.md
- interfaces/fiveg_gnb_identity/v0/schema.py
We decided to set the Tracking Area Code (TAC) as an integer instead of a string.
> Set TAC as integer in fiveg_gnb_identity relation interface

- interfaces/opensearch_client/v0/README.md
Minor cosmetics:
Removing the `tls` field from the example as it's not part of the specification.
Rendered version of the document can be viewed here:
- https://github.com/juditnovak/charm-relation-interfaces/blob/DPE-2799_removing_tls_from_example/interfaces/opensearch_client/v0/README.md
> [DPE-2799] [opensearch_client] Removing tls field from example

- interfaces/mongodb_client/v0/README.md
- interfaces/mongodb_client/v0/schemas/requirer.json
MongoDB Charms are using Juju Secrets in Charms Relations. This requires to follow a new protocol, described in this document.
Rendered version of the document can be viewed here: https://github.com/juditnovak/charm-relation-interfaces/blob/DPE-2800_mongodb_external_secrets_protocol/interfaces/mongodb_client/v0/README.md
> [DPE-2800][mongodb_client] Relation Secrets

- interfaces/mysql_client/v0/README.md
- interfaces/mysql_client/v0/schemas/requirer.json
MySQL Charms are using Juju Secrets in Charms Relations. This requires to follow a new protocol, described in this document.
Rendered version of the document can be viewed here: https://github.com/juditnovak/charm-relation-interfaces/blob/DPE-2798_relation_secrets_for_mysql/interfaces/mysql_client/v0/README.md
> [DPE-2798][mysql_client] Relation Secrets

- docs/json_schemas/openfga/v1/provider.json
- docs/json_schemas/openfga/v1/requirer.json
- interfaces/openfga/v1/README.md
- interfaces/openfga/v1/charms.yaml
- interfaces/openfga/v1/schema.py
Add openfga interface `v1`:
- Adds grpc endpoint
- Pass the URL as is instead of each component separately
- Adds the option to use a DNS hostname instead of IP
> Add openfga v1

- .github/workflows/discover.yaml
- interfaces/postgresql_client/v0/README.md
- interfaces/postgresql_client/v0/schemas/requirer.json
Adds `external-node-connectivity ` to the postgresql_client interface. This flag is needed for data-intgrator to be able to expose service from the Pgbouncer VM charm.
Implementation PR: https://github.com/canonical/data-platform-libs/pull/136
Specification: DA073
> [DPE-3450] Add external-node-connectivity field to postgresql_client

- docs/json_schemas/dns_record/v0/provider.json
- docs/json_schemas/dns_record/v0/requirer.json
- interfaces/dns_record/v0/README.md
- interfaces/dns_record/v0/schema.py
Follow up #145 
Change the requirer and provider databags. Remove the dns-domains entry for both and send instead a service-account entry for authenticating the requirer's request as a whole.
No charms implementing the relation have been released yet
> Redo dns-record interface

- tox.ini
> Use `ruff check`

- interfaces/postgresql_client/v0/README.md
- interfaces/postgresql_client/v0/schemas/provider.json
Adds new URI field, a libpg connection string, to the provider's side of postgresql relation.
Related to https://github.com/canonical/postgresql-k8s-operator/pull/545 and https://github.com/canonical/postgresql-operator/pull/527
> [DPE-2278] Add connection string to uri field in schema

- docs/json_schemas/vault_kv/v0/provider.json
- docs/json_schemas/vault_kv/v0/requirer.json
- interfaces/vault_kv/v0/README.md
- interfaces/vault_kv/v0/schema.py
This PR enables the usage of wrapping tokens by the Requirer part of vault_kv interface, as something optional.
This PR will enable `vault_kv` integration with charms that require a wrapping token instead of the role secret ID, like `maas-region`. MAAS can be integrated with Vault by providing approle details, as described in the relevant docs [section](https://maas.io/docs/how-to-integrate-vault).
> feat: Support for wrap TTL on vault_kv interface

- docs/json_schemas/sdcore_config/v0/provider.json
- docs/json_schemas/sdcore_config/v0/requirer.json
- interfaces/sdcore_config/v0/README.md
- interfaces/sdcore_config/v0/interface.yaml
- interfaces/sdcore_config/v0/schema.py
The `sdcore_config` relation interface was defined with an `_` not with a `-`. 
This PR:
- Aligns the documentation to the interface definition (use `_` instead of `-`) 
- Sets the NMS charm as provider
- Sets the AMF, SMF, AUSF, NRF, NSSF, UDM, UDR, and PCF as requirers.
> fix sdcore_config relation interface documentation

- docs/json_schemas/fiveg_f1/v0/provider.json
- docs/json_schemas/fiveg_f1/v0/requirer.json
- interfaces/fiveg_f1/v0/README.md
- interfaces/fiveg_f1/v0/interface.yaml
- interfaces/fiveg_f1/v0/schema.py
This PR adds definition of the `fiveg_f1` interface. 
In the 5G Radio Access Network architecture the `F1` interface is used to establish communication between the Central Unit (CU) and the Distributed Unit (DU) which are main building blocks of the gNodeB (the 5G base station).
> feat: Adds the fiveg_f1 interface

- interfaces/postgresql_client/v0/README.md
- interfaces/postgresql_client/v0/schemas/provider.json
Adds `subordinated` app and `state` unit level flags to the postgresql_client interface. Those flags are needed to indicate when a subordinated Pgbouncer VM charm is ready to accept connections.
Implementation PR: https://github.com/canonical/data-platform-libs/pull/180
Specification: DA104
> Subordinated router scale up

- docs/json_schemas/vault_kv/v0/requirer.json
- interfaces/vault_kv/v0/README.md
- interfaces/vault_kv/v0/schema.py
This requirer must provide a list of the IP addresses that it wants Vault to configure the authentication credentials with.
This should allow the requirer to be implemented in a way that allows providing different addresses so it works in both cases when it is deployed on the same model with Vault and when it is deployed in a cross model setup.
> Renames egress_subnet to egress_subnets and changes its type to array

- README.md
- docs/json_schemas/dns_record/v0/provider.json
- docs/json_schemas/dns_record/v0/requirer.json
- docs/json_schemas/kratos_external_idp/v0/provider.json
- docs/json_schemas/smtp/v0/provider.json
- docs/json_schemas/tracing/v2/provider.json
- interfaces/__template__/v0/interface_tests/README.md
- interfaces/cos_agent/v0/interface_tests/test_provider.py
- interfaces/ingress/v1/interface_tests/test_provider.py
- interfaces/ingress/v2/interface_tests/test_provider.py
- interfaces/prometheus_scrape/v0/interface_tests/test_provider.py
- pyproject.toml
- tox.ini
- utils/interface-validator.py
Adjust the versions to use ops-scenario 7.0 (including connected packages) and adjust the one test that needs adjusting (as far as I can tell, there are no others).
> chore: bump to Scenario 7

- interfaces/tracing/v2/interface.yaml
we're in the process of deprecating and retiring the tempo-k8s charm, replacing it with https://discourse.charmhub.io/t/charmed-tempo-ha/15531
the libs owned by tempo-k8s are now owned by tempo-coordinator-k8s.
> retired tempo-k8s

- run_matrix.py
Background: We cannot assign issues to anyone within the Canonical organisation who is not a writer in this repo.
After discussion with Ben, as a workaround, we will create issues, assign them to `charm-tech `members, and then mention the members from the maintainer team in the issue body/comment.
I could not test this change within my personal organisation, so we will have to merge and see how it works. As some manual test, I copy-pasted some of the code in my local console to see the rendered body, which seems fine:
```bash
>>> maintainer="observability"
>>> mention_team_members = ", ".join(["@" + member for member in get_team_members_from_team_slug(maintainer)])
>>> mention_team_members
'@mmkay, @Abuelodelanada, @simskij, @dstathis, @PietroPasotti, @michaeldmitry, @lucabello, …
```
> fix: assigning issues permission error

- interfaces/saml/v0/interface.yaml
- interfaces/smtp/v0/interface.yaml
[From commit history](https://github.com/canonical/charm-relation-interfaces/tree/4ebec2b8aeb1a724639ca4dfde4be92bf98cb447), both smtp and saml interfaces are maintained by the IAM team, but as confirmed by Massimiliano and David, the maintainer/owners of these two interfaces are the `platform-engineering` team. This team hasn't been created/updated in GitHub orgs yet, so at the moment, as confirmed by David, we set the maintainers as the `is-charms` team.
> chore: update saml and smtp interfaces maintainer

- docs/json_schemas/fiveg_core_gnb/v0/provider.json
- docs/json_schemas/fiveg_core_gnb/v0/requirer.json
- interfaces/fiveg_core_gnb/v0/README.md
- interfaces/fiveg_core_gnb/v0/interface.yaml
- interfaces/fiveg_core_gnb/v0/schema.py
This PR adds definition of the `fiveg_core_gnb` interface, according to the [TE126 - Orchestrating network configuration between the Core and the RAN](https://docs.google.com/document/d/1YsPgqfRDd9NX8j-BtJL4psvR1EJ7vTOvJGwm9k3iH_c/) specification.
This interface will be used by NMS (Network Management System) to configure the CUs (Central Unit) or gNodeBs, components of the RAN (Radio Access Network) in a 5G Network.
> feat: add the fiveg_core_gnb interface

- docs/json_schemas/fiveg_rfsim/v0/provider.json
- interfaces/fiveg_rfsim/v0/README.md
- interfaces/fiveg_rfsim/v0/schema.py
This PR extends the fiveg_rfsim interface according to the [TE126 - Orchestrating network configuration between the Core and the RAN](https://docs.google.com/document/d/1YsPgqfRDd9NX8j-BtJL4psvR1EJ7vTOvJGwm9k3iH_c/) specification.
This interface is only used internally between the DUs (Distributed Unit) and the UEs (User equipment) to orchestrate network configuration for the Charmed Aether SD-Core.
> feat: Extend fiveg_rfsim interface

- docs/json_schemas/tempo_cluster/v1/provider.json
- docs/json_schemas/tempo_cluster/v1/requirer.json
- interfaces/tempo_cluster/v1/README.md
- interfaces/tempo_cluster/v1/interface.yaml
- interfaces/tempo_cluster/v1/interface_tests/test_provider.py
- interfaces/tempo_cluster/v1/interface_tests/test_requirer.py
- interfaces/tempo_cluster/v1/schema.py
- utils/interface-validator.py
As per changes in https://github.com/canonical/cos-lib/pull/95, the `tempo_cluster` interface removed `tracing_receivers` field in favour of 2 new additional fields `charm_tracing_receivers` and `workload_tracing_receivers`.
Add `v1` schema version for `tempo_cluster` interface.
> Update `tempo_cluster` schema

- docs/json_schemas/grafana_datasource/v0/requirer.json
- docs/json_schemas/grafana_datasource_exchange/v0/provider.json
- docs/json_schemas/grafana_datasource_exchange/v0/requirer.json
- interfaces/grafana_datasource/v0/README.md
- interfaces/grafana_datasource/v0/interface_tests/test_requirer.py
- interfaces/grafana_datasource/v0/schema.py
- interfaces/grafana_datasource_exchange/v0/README.md
- interfaces/grafana_datasource_exchange/v0/interface_tests/test_provider.py
- interfaces/grafana_datasource_exchange/v0/interface_tests/test_requirer.py
- interfaces/grafana_datasource_exchange/v0/schema.py
Adds an identifier for the grafana instance on which the datasource is registered, so the datasources themselves can determine whether cross-comparing will have any sense, because their datasources are known to the same Grafana instance (or not).
reference implementation: https://github.com/canonical/grafana-k8s-operator/compare/main...add-grafana-uid-to-DS
> added grafana uid

- docs/json_schemas/ldap/v0/provider.json
- interfaces/ldap/v0/README.md
- interfaces/ldap/v0/interface.yaml
- interfaces/ldap/v0/schema.py
Small PR that corrects the `ldap` interface. The interface originally had the `url` field typed as `url: AnyURL`, however, the `url` field is now actually the `urls` field as is typed as `list[AnyURL]`. Providers like glauth-k8s can provide multiple LDAP server URLs now rather than just one. Here's the relevant block of code in the `ldap` library implementation:
https://github.com/canonical/glauth-k8s-operator/blob/73209477bd4ef533b88f543d4c7c24a7bf9dffee/lib/charms/glauth_k8s/v0/ldap.py#L230-L231
Providing multiple server URLs is necessary for HA GLAuth deployments where each GLAuth instance runs independently and uses an HA backing database such as Postgres or MySQL: https://glauth.github.io/docs/high-availability.html
Also, I added the SSSD operator as an example implementation of a …
> fix(ldap): update `url: AnyURL` to `urls: list[AnyURL]`

- docs/json_schemas/cloudflared_route/v0/provider.json
- interfaces/cloudflared_route/v0/README.md
- interfaces/cloudflared_route/v0/interface.yaml
- interfaces/cloudflared_route/v0/schema.py
Add the interface definition for the `cloudflared_route` integration, as used in the `cloudflared` charm and the `cloudflare-configurator` charm.
> Add the `cloudflared_route` interface

- docs/json_schemas/tempo_cluster/v1/provider.json
- interfaces/tempo_cluster/v1/README.md
- interfaces/tempo_cluster/v1/schema.py
the tempo-cluster schema [is gaining a new field](https://github.com/canonical/cos-lib/pull/131): the worker_ports field.
Updated the schema to reflect that.
> update tempo-cluster schema

- interfaces/mysql_client/v0/README.md
- interfaces/mysql_client/v0/schemas/provider.json
- interfaces/postgresql_client/v0/README.md
- interfaces/postgresql_client/v0/schemas/provider.json
Specification: DA158
Charm lib PR: https://github.com/canonical/data-platform-libs/pull/206
Adds URIs field to Mysql interface and read only URIs to Postgresql interface
> [DPE-6555] Add URIs and read only URIs to Postgresql and Mysql

- docs/json_schemas/etcd_client/v0/provider.json
- docs/json_schemas/etcd_client/v0/requirer.json
- interfaces/etcd_client/v0/README.md
- interfaces/etcd_client/v0/interface_tests/test_provider.py
- interfaces/etcd_client/v0/schema.py
* [`docs/json_schemas/etcd_client/v0/provider.json`](diffhunk://#diff-8d5e8d381050d692bea837f97d41dbc9f508b636ff3ff5e8814fb9436c94665cL36-R36): Updated the example for `endpoints` to remove the protocol prefix.
* [`docs/json_schemas/etcd_client/v0/requirer.json`](diffhunk://#diff-528375a881aaa038937eb20fb9538cbc76daf7c63e381a2a135f5185191eede8L50-R51): Expanded the `requested_secrets` example to include additional fields.
* [`interfaces/etcd_client/v0/README.md`](diffhunk://#diff-80ceedc75627d6862a812581be0880612cd45d932619ca18d273a54ee6d76591L32-R51): Enhanced the documentation to clarify the expected fields for both the Provider and Requirer, including new fields for Juju Secrets and updated descriptions for existing fields. [[1]](diffhunk://#diff-80ceedc75627d6862a812581be0880612cd45d93 …
> Update etcd client interface

- README.md
I was initially only going to update the Ops link in the README to point to documentation.ubuntu.com instead. Then it occurred to me that it might be more useful to link to our how-to doc about interface tests, instead of the reference docs for Scenario.
> docs: replace ops.testing link by how-to link

- .github/workflows/dispatch-matrix-tests.yaml
- .github/workflows/matrix-tests.yaml
This PR moves the logic to invoke the matrix tests for an individual interface to a reusable workflow, and allows specifying the repository and branch to fetch the test and interface definitions from. This will allow the tests added by a PR to be (manually) run in the CI context before merging, instead of only being able to test them locally.
Here is [a manual run of the matrix tests workflow from my fork](https://github.com/james-garner-canonical/charm-relation-interfaces/actions/runs/16741618134), and here is [the most recent run of the same workflow on main](https://github.com/canonical/charm-relation-interfaces/actions/runs/16711095816). The same interfaces are passing and failing in both cases.
> ci: let matrix tests run for a single interface from a PR branch

- .github/workflows/dispatch-matrix-tests.yaml
`run_matrix.py` uses Python 3.9+ features (`pathlib.PurePath.is_relative_to`). That code only triggers if `charm_root` is set, but I'm still surprised that this hasn't been an issue yet. It was noticed in #295. Are there any concerns with bumping the Python version? I've verified [here](https://github.com/canonical/charm-relation-interfaces/actions/runs/17285932508/job/49063088437?pr=297) that the matrix tests all pass with this change.
> ci: bump matrix tests Python version 3.8 -> 3.10

- .github/workflows/dispatch-matrix-tests.yaml
This PR bumps the Python version for matrix tests all the way to 3.12 since the `litmus_auth` tests won't pass without this (#295), and all the other tests seem to be in a shambles anyway.
> ci: bump Python version to 3.12 since some tests require this

- .github/workflows/dispatch-matrix-tests.yaml
We recently recommended using `poetry export ...` in `pre_run` to get Poetry style deps into `requirements.txt` format for the interface tests, but the `poetry-plugin-export` Poetry plugin is required to provide the `export` subcommand. This PR installs the plugin at the same time as we install `poetry` for interface tests.
> ci: install poetry-plugin-export for poetry export
